import './globals.css'
import "../public/extlib/fluent/FluentSystemIcons-Resizable.css"

// import Header from './header'
// import Footer from './footer'
import Aside from "@/components/Aside/Main";
import SideBtn from "@/components/Aside/SideBtn";
import SideLink from "@/components/Aside/SideLink";

export const metadata = {
  // title: 'NotePad',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-200 text-gray-800'>
        <section className="w-full
      h-screen flex items-center justify-center">
          <Aside>
            <div className="space-y-1 w-full bg-slate- font-medium py-2">
              <SideBtn  text={"New note"} icon={"ic_fluent_add_20_regular"} style={"border border-blue-200 bg-blue-200/20 hover:bg-blue-200 text-blue-500 pr-4 mb-3"}/>
              <SideLink text={"Home"} href={"/"} icon={"ic_fluent_home_20_regular"}/>
              <SideLink text={"Settings"} href={"/settings"} icon={"ic_fluent_settings_20_regular"}/>
              <SideBtn  text={"Help and feedback"} icon={"ic_fluent_info_20_regular"} style={"w-full"}/>
            </div>
          </Aside>
          <main className="w-full md:w-9/12 h-full md:pr-1.5 md:py-2"></main>
          {children}
        </section>
      </body>
    </html>
  )
}
